### PR TITLE
[RFC] enable autoloader to load other environments than .env

### PR DESCRIPTION
**Pull request by michz**
I very much like the ability to define the environment variable `SHOPWARE_ENV` and thus the ability to use different configs.
But: I also like the idea to define configuration in `.env`. This is especially useful if you want to use the configuration additionally in shell scripts (as we do in some development environment/automation).

This PR suggest a method to transfer the the idea of `SHOPWARE_ENV` to `.env` files.

It works as follows:

If `SHOPWARE_ENV` is not set, only `.env` file is loaded.
If `SHOPWARE_ENV` is set (for example to `dev`) and a file called `.env.dev` exists, it will be loaded first. After that the file `.env` is loaded overriding existing environment variables.

This way you can define configuration for different environments (staging, production, dev, test, ...) and keep them in source control and switch between them by settings `SHOPWARE_ENV`.

This is a request for comments. I'd appreciate to read your opinions.
(This includes the naming of the file. Feel free to provide alternatives, for example if you like `dev.env` or yet another more.)

### CODE REVIEW

**Comment by michz** [comment]
Hi @shopwareBot , thanks for your reply. I hope you understand that I just talk to real people not hiding behind a quasi-anonymous account.

**Comment by michz** [comment]
Hi @shopwareBot , @shyim , @soebbing , @PaddyS , ... , I'm very sorry but in my humble opinion this is not the way Github (discussion tools) is intended to be used.

I can only repeat: I hope you understand that I just talk to real people **not hiding behind a quasi-anonymous account.**
If you want to ask and discuss, please do not use a "bot" account.

**Comment by PaddyS** [comment]
Hey @michz,

can you be more precise on your specific use case?
Usually .env files are just a workaround for actual environment variables of your webserver e.g.

**Comment by ThomasHartz** [comment]
@PaddyS has a point.

There is a considerable number of projects around, that allow and even emphasize environments like dev test and  prod, i don't think, that it is a good idea, to keep the environment files in the project.
Especially once you armed those environments with credentials.
This approach is misleading people to check in credentials in source control and therefore dangerous.
@michz What do you think about sourcing your env on the machine you are running on?

**Comment by michz** [comment]
That's a good point, in practical environments I am with you.
In this context, however, I don't really understand why your skeleton is based on a `.env` file that is sourced and used in your default `config.php` .
I think if you discourage this behavior you should not do the same thing in your default project template.

Perhaps it would be better if we state this clearly in the `.env.example`.
Seeing the dotenv package loaded via composer and the `.env.example` in the skeleton's root (mis)leads users (including me ^^ ) to the assumption this is a suggested way of using it.

**Comment by soebbing** [comment]
As discussed, `.env` files are intended as a (local) workaround for real environment variables on production systems. But I agree with you, @michz, that this could be pointed out more clear to the developers using this project.

Feel free to create a little PR adding a comment to the README and `.env.example`!

**Pull request closed without merging**
