### PR TITLE
Feature: Enable additional project-specific config.php (not tracked in repo)

### PR DESCRIPTION
**Pull request by tvanekeris**
Feature: Allow for an additional project-specific config file (config.php) that is no tracked in either the shopware nor the composer-project repository

### CODE REVIEW

**Comment by soebbing** [comment]
I'm not sure I get the use case: normally your clone of this repo would be your project where you can modify the config.php to your needs. Why add another one?

**Comment by tvanekeris** [comment]
Hi Hendrik,

thanks for the quick response!

The idea is that we can pull in the changes from this repository (because we already had the case that this repository gets updated) without overwriting any custom project & environment specific files. My idea is this can be handled in a similar logic as with the whole "shopware as a composer package" where the project-specific settings (such as a composer.json) are independent from shopware's own composer.json.

In the current logic, if we update the config file (app/config/config.php) then we will need to solve a merge conflict when this repository gets updated (because you e.g. change to better default config options).

Is that understandable? There also might be a better way to achieve our goal :-)

Thanks and BR
Tilo

**Comment by bcremer** [comment]
This repository is not meant to be cloned (`composer require shopware/composer-project`), but used as a template `composer create-project shopware/composer-project` for your own shopware project.
Upstream changes to this template project should be tracked manually and backported to your custom shopware project.

**Comment by viosys** [comment]
I can only agree with Tilo, because we want to do the same.

**Comment by hranicka** [comment]
+1

Since we can have different configuration in different environments (dev, stage, live, ...), this would be really helpful.

**Comment by soebbing** [comment]
As @bcremer already said: This project is a template which you should modify in your projects as you see fit. That's where I would see such a feature, but I don't think that such a check should go into this template.

**Pull request closed without merging**
