### PR TITLE
[BUGFIX] Removed --mode=update from sw:migrations:migrate, cause migr…

### PR DESCRIPTION
**Pull request by wolv-dev**
…ation won't be executed correctly

### CODE REVIEW

**Comment by soebbing** [comment]
Hi @wolv-dev, can you describe what it is exactly what is going wrong? Removing the parameter runs the migrations for an install, that is not what you would want to do on an update.

**Comment by wolv-dev** [comment]
@soebbing 
This command isn't running the migration at all. Nothing will be executed, just like it ignores the migration numbers.
This will lead to errors when database fields or even database tables doesn't exist on the next step for generating cache/attributes. We (me and my colleagues) needed to manually execute sw:migrations:migrate during composer update and start composer update again, so that all other commands will be executed.

For example, this is the recent error that occured not only for me, but for my colleagues as well:
`The target-entity Shopware\Models\Attribute\Shop cannot be found in 'Shopware\Models\Shop\Shop#attribute'.`

**Comment by soebbing** [comment]
@wolv-dev I see. This particular problem results from an inconsistent state during the migration when a new attribute is being added.

But I think this change would break in a lot of unexpected ways when migrations differ between installations and updates. A better fix would be to clear the caches hard (as in: using an `rm` command) before and after running the migrations

**Comment by wolv-dev** [comment]
I updated the PR to clear the cache before the migration, but this needs some more propper testing.

**Pull request closed without merging**
