### PR TITLE
Implements build scripts as php commands

### PR DESCRIPTION
**Pull request by jkrzefski**
When I was using the composer project different server environments, I experienced some problems with the build scripts that are referenced in the composer.json file. If the desired php binary to execute is not in the `PATH` variable, the scripts cannot find it. For composer in general this problem is easy to overcome as you can execute composer itself with a binary of your choice like this: `/opt/plesk/php/7.2/php $(composer) install`. But when composer executes shell scripts which in turn execute another php command, they use the first php binary they find in the `PATH`. Composer already has a solution for this: `@php`. Scripts that are run with this will use the same php binary composer was run with. So I took the build scripts and made symfony commands out of them.

I made another console to have some isolation from the normal shopware console and made the new command available only there. They should behave almost exactly the same as the original scripts. I still kept those around for backwards-compatibility reasons.

### CODE REVIEW

**Comment by JoshuaBehrens** [comment]
I'd like to see a deprecation hint in the bash scripts when the composer scripts should replace them. I really know the hassle myself. The swCommand bash function always takes the wrong php version :anger:

**Comment by EvilBMP** [comment]
Why don't you just create a directory like `bin` or `sbin` in your user home and create a symlink to `/opt/plesk/php/7.2/php` ?
Then simply add this directory to `$PATH` via `.bashrc` or `.bash_profile`...

I usually have something like this in there:
```
PWD=$(pwd)

# add project binaries to path
if [ -d "$PWD/bin" ]
then
  export PATH=$PWD/bin:$PATH
fi
if [ -d "$PWD/web/bin" ]
then
  export PATH=$PWD/web/bin:$PATH
fi
if [ -d "$PWD/web/vendor/bin" ]
then
  export PATH=$PWD/web/vendor/bin:$PATH
fi
```

Don't get me wrong. It's not, that I don't like the idea of having Symfony CLI scripts instead of bash scripts. Just another way to solve your given problem.

**Comment by JoshuaBehrens** [comment]
This would work for me to define php for each user like this. Good hint. I will try that one out. I hope cronjobs will use this as well

**Comment by EvilBMP** [comment]
Well, cronjobs is another case. Normally cronjobs don't run in an interactive user shell. So the `.bashrc` or `.bash_profile` or `.profile` etc. won't be recognized.

But you can combine the above lines into a single line for your crontab entry:

`PWD=$(pwd); [ -d "$PWD/bin" ] && export PATH=$PWD/bin:$PATH; YOUR_CRONJOB_CMD`

Or simply call:

`/path/to/your/php YOUR_CRONJOB_CMD`

Because normaly you should only have one entry for your applications cron cli endpoint.

You can also make a `cron.sh`, where you put in the lines from my first comment and below you call your cronjob command(s). This way is sometimes necessary, if your hosting configuration interface does not allow whitespaces in the cronjob entry command form field.

**Comment by JoshuaBehrens** [comment]
I do host on my own using Plesk but there are different applications running in different php setups depending on the project dependencies. Currently my crontab does look like `/path/to/your/php YOUR_CRONJOB_CMD` but it would be nice if this can profit as well.

**Comment by jkrzefski** [comment]
I had some time to tinker around with this solution a bit more and inspired by #33 I added a better support for non-interactive mode. With my latest changes it is now really easy for me to run the installation unattended. Whether on a server to quickly spawn a system or to easily reset my development environment. I hope this can provide more of a benefit to the project, than the mere migration of existing scripts.

**Comment by jkrzefski** [comment]
Hey @shopwareBot,
are you still on it?

**Comment by soebbing** [comment]
Hi @jkrzefski!

By now I had a good look at your script and while it get's the job done, it isn't all I had hoped for. :)

I really would like to use the opportunity to separate the _necessary_ environment variables (`DATABASE_URL`, `SHOPWARE_ENV`, `TRUSTEDPROXIES`) from the ones that up to now are just used to provide some parameters to the setup script (`ADMIN_*`, `SHOP_URL`, `IMPORT_DEMODATA`).

I really think these variables should be replaced by some command line parameters which then could just be passed down the the existing commands.

What do you think?

**Comment by jkrzefski** [comment]
@soebbing I like that idea. Those variables are basically for one-time usage and therefore have no need to be stored. I will make these changes. Thank you for your feedback.

**Comment by jkrzefski** [comment]
@soebbing Please take a look at my latest changes. I have to thank you a lot for your suggestions. The new additions really make it cleaner and more flexible to use. The `sw:build:install` command is now basically what `./psh.phar init` is for the main repository: A complete reset of your installation that does not lose your database credentials and can easily be run in non-interactive mode by adding the `-n` option. I really like this outcome and I hope I did everything the way you imagined it.

**Comment by jkrzefski** [comment]
So, not trying to be rude or anything, but... Any news on this one? Just curious.

**Comment by soebbing** [comment]
I'm really sorry it takes us so long. Your PR is not forgotten, we just don't have the time currently. 😢

**Comment by jkrzefski** [comment]
@soebbing Not a problem. I can only imagine the amount of work you guys currently have on your desk.

**Comment by shyim** [comment]
The problem is now fixed with Composer 1.9.0 https://github.com/composer/composer/releases/tag/1.9.0

We have to just use PHP_BINARY env

**Comment by JoshuaBehrens** [comment]
So shopware composer requires a composer 1.9.0 executable to work more flawless?

**Comment by jkrzefski** [comment]
So what does this mean for this PR? Do I have to make some changes or will this PR be dismissed? Is it even desirable to have build scripts in PHP?

**Comment by JoshuaBehrens** [comment]
I prefer to keep as less languages as needed in a project. So if we can reduce the amount of bash in a composer project we gain more compatibility and a more unified way to change things in this application

**Comment by shyim** [comment]
It feels like :joy: 

image

**Comment by JoshuaBehrens** [comment]
Yes. It was like this when the bash scripts have been introduced here. This is a php project and someone liked to use bash instead. I just want to point out that there is a swCommand function in these bash scripts to call bin/console to execute already given php procedures.

**Comment by shyim** [comment]
I have fixed it by using the passed Composer PHP Binary. Sorry for the long wait!
Commit: https://github.com/shopware/composer-project/commit/b3bbb8ac35bcc13d709bd8fb641e9a8c7d6de695

**Pull request closed without merging**
