### PR TITLE
fix(): quote paths to allow install path to contain spaces

### PR DESCRIPTION
**Pull request by RafaelKr**
I tried to create a project in a folder which contained spaces and got an error. This PR quotes every usage of the root path to prevent that.

Error:
```
> ./app/bin/post-install.sh
Creating symlinks in /home/rafael/coding
folder/shop/app/bin
./app/bin/functions.sh: line 173: cd: too many arguments
Script ./app/bin/post-install.sh handling the post-root-package-install event returned with error code 1
```

image

### CODE REVIEW

**Comment by RafaelKr** [comment]
Another suggestion I have is that it maybe would make more sense to output the following after running the `composer install`:

```
Please run app/bin/install.sh manually to finish your installation

Have a nice day!
```

**Review by soebbing — APPROVED** [review]

**Comment by soebbing** [comment]
Hi @RafaelKr, thank you very much for your contribution and sorry it took so long to be merged! 💙 🙏 🎉

**Comment by RafaelKr** [comment]
Thanks for merging! (Although it really took a long time 😄 but yeah... priorities.)

Did you also see my comment about outputting the instructions after the `composer install`? This can be easily missed right now.

**Comment by soebbing** [comment]
I don't think that the `install.sh` should be run after a `composer install` in general. `install.sh` is only supposed to be run once, `composer install` can be run multiple times (think about the deployment of a shop with a changed 'composer.lock'-file).

**Comment by soebbing** [comment]
I created a new pull request #48 which might help with your issue?

**Comment by RafaelKr** [comment]
I think we talk past each other.

What I mean is that if you have a look at my screenshot in the opening post of this PR you can see, that the Shopware-Banner and the instructions about running install.sh are getting printed as part of the `composer install` when the `shopware/composer-project` package is installed. And as `shopware/composer-project` is the first installed package it is printed before all the other packages are installed and could be missed when someone has a small terminal and doesn't have an eye on the install process.

But maybe a solution would be to move this code https://github.com/shopware/composer-project/blob/771aaa08d40c8e21281e98d40bb0e92d1bec0ecc/app/bin/post-install.sh#L31-L40 to a `post-create-project-cmd.sh` file which is then executed on the `post-create-project-cmd`-hook of composer (https://getcomposer.org/doc/articles/scripts.md#command-events)

Or alternatively run the install.sh directly from that hook.

Disclosure: I didn't test that hook, but from my understanding it should run exactly once, as last step of the create-project command.

**Comment by RafaelKr** [comment]
> I created a new pull request #48 which might help with your issue?

I think I never had a problem with this command, so I can't say anything about it.

**Comment by soebbing** [comment]
I think there is something different in general, have a look at how the installation looks on my machine:
image
I am not exactly sure why they are different...

**Comment by RafaelKr** [comment]
Okay, that's interesting. I have to try that myself again.

**Comment by soebbing** [comment]
It might be that I had an old version in the composer cache. Could you try to run the command in the screenshot and tell me if it works for you?

**Comment by RafaelKr** [comment]
Now I get the following error:
```
$ composer create-project shopware/composer-project my_project_name --no-interaction --stability=dev
Installing shopware/composer-project (dev-master 771aaa08d40c8e21281e98d40bb0e92d1bec0ecc)
  - Installing shopware/composer-project (dev-master 771aaa0): Cloning 771aaa08d4 from cache
Created project in my_test_project
> ./app/bin/post-install.sh
Creating symlinks in /home/rafael/coding/my_project_name/app/bin
cp: cannot stat 'vendor/shopware/shopware/themes/Gruntfile.js': No such file or directory
Script ./app/bin/post-install.sh handling the post-root-package-install event returned with error code 1

```

This is probably related to #46

**Comment by soebbing** [comment]
You're right, that error is related to PR #46. In my own PR there is a fix for it, have a look at my screenshot: the change hasn't been merged yet and you need to reference the feature branch to test the change.

**Pull request merged**
