### PR TITLE
Load configuration files from project root

### PR DESCRIPTION
**Pull request by thampe**
Hi,

currently the composer shopware version can not load config.php and config_*.php from the project root. This PR adds this functionality.

If it can be achieved in an other way please let me know. Thanks.

### CODE REVIEW

**Comment by marvinhinz** [comment]
👍

**Comment by soebbing** [comment]
Can you please explain the reason why you think this change is necessary and what you are trying to achieve with it?

With this composer-project we tried to implement current best practices in web development by using environment variables instead of configuration files (at least for sensitive information like database credentials). This PR looks like a step in the wrong direction in this regard.

**Comment by thampe** [comment]
Hi, 

thanks for the quick feedback. I need to setup a local dev environment. As far as I unterstand the code there is no way to set this with an .env file and not change the `app/config/conifg.php` file: https://developers.shopware.com/developers-guide/shopware-config/#example-development-config

**Comment by soebbing** [comment]
Hi @thampe, maybe this PR from @jkrzefski might show you a way how you can achieve a setup like this: https://github.com/shopware/composer-project/pull/12/files

Also: You can easily implement your own env-variables and check them in the existing `app/config/config-php` e.g. for providing the data for memcache, redis or ES instances.

**Comment by marvinhinz** [comment]
What would be the recommended way to override settings in vendor\shopware\shopware\engine\Shopware\Configs\Default.php that are enviroment dependent? 

Is it okay to modify the app/config/config.php and add a line like this:

image

It somehow feels strange to edit a config file that was shipped with this project to override such settings. 
Maybe its possible to auto-load _all_ config values from the .env file and merge it with the default config?

**Comment by thampe** [comment]
Hi, 

thanks, I understand that I can solve my problem by changing the `app/config/config.php`. But I think there should be a way to change  arbitrary configuration values based on your enviorment without explicitly the `config.php` for it. Like it was possible on the "old"/non-composer version.

**Comment by soebbing** [comment]
@marvinhinz Modifying the `app/config/config.php` is totally fine. The whole idea of this project is to be a template how to use Shopware with composer, nothing more. You are free to modify it in your project as you see fit.

The downside is: as a template, you shouldn't simply clone the repo and pull changes later on, but rather track changes manually and integrate things you like into your project where necessary.

Of course you could try to merge all values from environment variables into the config, but I wouldn't recommend it. .env files themselves are only a workaround for real env variables and should only be used in dev environments.

**Comment by marvinhinz** [comment]
@soebbing Okay, thank you for the clarification!

**Comment by soebbing** [comment]
@thampe I would argue that the concept of different config files was only necessary because we didn't have support for environment variables yet. 

I can see that multiple config files might improve overview of differences in the environments, but I would not want to include any files in the project root as this might be misunderstood as this is how to configure the project.

**Pull request closed without merging**
